language: java
sudo: required
env:
  global:
  - secure: oFbq1a/S9qXO62Zk4YfvVQ7tW/fJiwTkrcR/pvMW502nw4iWVDjZAf0vnJ1sdyzPqlW32THWD4k514nPDAQ91ZpXCrzsi2BxCZTJ8wGPQRMtL4rSP45w1Ug076QOLMwR6qrSjIsq4hywBIyhNQjeQCN4nUSzLMly6S+Tzbt3Cu62kxZGEg2HaV//IV1vwqLKF8yNDrHpxQ/5wHw/I8mWKIMso8Zil+oZXlc8tneFhtGuWDsyUb7JI09fdhzq1FNaPjYPCVS+U4JnwEqv9/dWK/tDWKMIQRFwmAxSy0tix90QeU4pMmML4pYRZvDULoq5rCb9eLB4mopm5W4kd4FVZoIyT9hodHorvqMo8hNsRJLBAEUfI5JjjHOtlNgT6mYuWieZBiM+q1qZl2IIxeHJpxircGi780L09s9fH9NJj28jwFTTnQBUg4jA7SCO06jQ/R/2oPjKvKnqgX5omfNXx3Dn6ucSuU11lqVRAhjFu/+p/sqXsKBXF8HYfSGYfyejj98SlHVUfUGDvVmgFxqjMITmkcQzNcXPOxZVHUcDIxu1MSHl0imwOMwNGBaD4W5Oc89fyamYb0fvfUWCgk/TNuChWcxZeynumSQCTOlRn2UsQn7JYT+QqWo9zFWVs4hPeqPDYHHMwHOmcPdhGOkv2JF7M5T7qwQie/OUkd1BCIM=
  - secure: sODpQU699Hqc5XHGiQgZ7v8a6g38XpnFeCqZx3pGYrC6UGxEiQj5yjP2N4ouNZ7Wgv3FbA1RCiqOiIQ/oUSkgagFUiiTM+7xd2FD+pOciSTk1/4stADZl4rV9nDxfktZ2FNSB5FkzhLHnSizxBZpz2CkGeIzf2m9ac5m3nV5vmHUvwvgMSYedIOjjZ9V+cElmbnXcBQBNbYsq66tsYacpsw0Dc26gp69z5jpKHzmpO9A2f8RMFLKZfu790i2QcOPoL1TV3PH3NtYYif7jCNkbH0DrtJ33frkgI/Xf8dL54u7IazWmSMr/T/c5c70Gssl/Rs9Trj/3kxd64inTweE3dcUn9kJ4jx6hupYLSnbOxJ+jy48Fq0fixm3p9CV/j3uPwpsz11hX3BKuCpCVxpIZBonnidlEQEagYu26w2bvqL+0M5ODH6FL6Uj980sXQ7wA6r8sEFIhOrFWNcDGME9cM60LkrP8PCzTD2F3pQO0/OrGF5mPfTaWycbgiqzPspLFzSzx2n4CV4yw0iFjROK7vRU2SQlKizAIwsDLxeQDjRyPVibPki1F5nJJ1ZF1q/vOHKoXmNKQjlVoNkuwp7/cCL1PY5bw1Qyzm/FfY+PjmkWH9Ho6fxU/MAN7Po5IoSMBTgyZ/u8us3kD+chHdjrLqOGPLq/kAhEJYsj6rWD7lg=
  - secure: JO8VpT066hHOaUnhlC4G/DOVPV7L4CnkNrnbAR2c5BCUmpcrAmXVfzApQGVOZkOx9cjHRJoinoJPIoaNawG+Smi4Z5FNLnEB4hvI94OmlwSyXrM4lDmwpA7oHt+nlPlxKC0Jeb+G/vT9itJAiMLr4nX4Z+zGEHQ0ugByijtw2K8su6Z1Qz24J9JAkmrO2XP+ojiq0oP4a0O/kpE0sbzsuPO+K4mxuOqxK+094ECAYC71hQr7RFEu+hD2WIhLwb6kt4Vqk4jIIG/0mOdxjMGXD/99F1CwBpB+Qi9jjm4ndM570VgyBNTI/G9Zfo2A+S4Sl8aeKeHSQaxweQEKnF0Ri6yvLtPHWF56A+I6XMTYiBptMgFBNKGyYHMOAVCskNWVrL2oADWNv0/pPWRCXfjSJdy+XqX5xBHflGeVBG+uoqx31bUk+tJsEuhN2hhE2Di8AKtu8lrgeY8Qn3jBo51AJqFyrO1yY45z6cXZ4Zh8dTo2TCyjvLSldRg55rQi+sRGD1Uv1ZRIl70hMQGz9z4obis1nWLi+Cay9YV7wtW3HLG6QYBNlknum8BQPVYTkaysa/XwcF8bLybKm0RD8l82/yqPvIt4uW6Nifc2FJUjTDHCGY4noicOi2lYELpb6gqgHzM9whffgnCULmMKAgyjI83JqWNH7msrAroC0bQFzkc=
  - export REPO=klkelley/http-server
  - export GITSHA=`git rev-parse HEAD`
jdk:
  - oraclejdk8

before_install:
  # Download desired version of Gradle
  - wget http://services.gradle.org/distributions/gradle-4.6-bin.zip
  - unzip -qq gradle-4.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v

services:
  - docker

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" != "master" ]; then echo "${TRAVIS_BRANCH}.latest"; fi`
  - export MASTER_TAG=`if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "${TRAVIS_BRANCH}.latest"; fi`
  - export SHA=`if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "${TRAVIS_BRANCH}.${GITSHA}"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PWORD
  - gradle buildImage
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:$MASTER_TAG
  - docker tag $REPO $REPO:$SHA
  - docker push $REPO

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"